export const API = 'https://www.thecocktaildb.com/api/json/v1/1/filter.php?c=Cocktail'
export const API_FOR_SEARCH_COCTAILS_ByName='https://www.thecocktaildb.com/api/json/v1/1/search.php?s='
export const API_Alcoholic= 'https://www.thecocktaildb.com/api/json/v1/1/filter.php?a='
export const API_Details='https://www.thecocktaildb.com/api/json/v1/1/lookup.php?i='
export const API_Ingridient='https://www.thecocktaildb.com/api/json/v1/1/search.php?i='